config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  resources :works
  resources :blogs
  resources :quotations
  resources :contacts
  root 'pages#home'
  get 'marketing' => 'pages#marketing'
  get 'company' => 'pages#company'
  get 'news' => 'pages#news'
  get 'contact' =>  'pages#contact'
  get 'web' => 'pages#webdesign'
  get 'projects' => 'pages#projects'

end

app/views/partials/_company_content.html.haml
%section#company-info.valign-wrapper
	.company-bg.center-align
		%h1.center-align IN OUR FLESH AND BLOOD
		%h3.center-align We are born for creativity
		%a.waves-effect.waves-light.btn{:href => "#"}
			%i.material-icons.large.left pageview
			Learn more
.container
	.company-text
		%p.text-flow
		Among everything we do ,quality and customer care comes first, we focuses on the things that matter to our clients by focusing on their preceding needs and goals and how to achieve them. most of our clients use us to manage every aspect of their online presents from designing and developing their website to providing a range of advertising platform and support to help them achieve their goals. we are aware that digital marketing are so complicated and we will make sure we don’t confuse you by speaking the language we both understand no complex acronyms.

		we provide services across a huge range of industry, from small online shop to large business.

app/views/partials/_contact.html.haml
.our-contact.row
  .contact-head.container
    %h1.text-center #get in touch
  .contact-us
    .call-us.col.s12.m6.l3
      .cover-blind
        %i.fa.fa-phone-square
        %h4.text-center Call us
        %a{:href => "#"} 
          %h6.text-center 02076352679, 07853292983
          %p.text-center one of our team will answer your call
    .email-us.col.s12.m6.l3
      .cover-blind
        %i.fa.fa-envelope-square
        %h4.text-center Send Email
        %a{:href => ""} 
          %h6.text-center design@miscotech.co.uk
          %p.text-center we will reply your email quickly
    .tweet-us.col.s12.m6.l3
      .cover-blind
        %i.fa.fa-twitter-square
        %h4.text-center Tweet us
        %a{:href => "#"} 
          %h6.text-center @onklickmedia
          %p.text-center we will definitely tweet you back
    .facebook.col.s12.m6.l3
      .cover-blind
        %i.fa.fa-facebook-square
        %h4.text-center Find us
        %a{:href => "https://www.facebook.com/onklickmedia", target: 'blank'} 
          %h6.text-center Onklick media
          %p.text-center you can also message us on facebook 
.form-hidden
  .form-hidden-cover
    .boder-line
      .form-drop-down.container
        %p Got New or Existing project for us please Call our team on 02076352679
        %h3 OR
        .form-button
          %a.page-scroll{:href =>"#page-top"}
            %h3 Get instant Quote

.caret-pop.container
  .arrow-down
/ #contact-form.container
/   #contact
/     %h1.center-align SEND US MESSAGE
/   %form.col.s12
/     .row
/       .input-field.col.s6
/         %input#first_name.validate{:type => "text"}/
/         %label{:for => "first_name"} First Name
/       .input-field.col.s6
/         %input#last_name.validate{:type => "text"}/
/         %label{:for => "last_name"} Last Name
/     %br/
/     .row
/       .input-field.col.s6
/         %input#email.validate{:type => "email"}/
/         %label{:for => "email"} Email
/       .input-field.col.s6
/         %input#telephone.validate{:type => "text"}/
/         %label{:for => "telephone"} Telephone
/       %br/
/       .row
/         .input-field.col.s12
/           %textarea#textarea1.materialize-textarea
/           %label{:for => "textarea1"} Message
/       %br/
/       %button.btn.waves-effect.waves-light{:name => "action", :type => "submit"}
/         Send Message
/         %i.material-icons.right send
/     %br/
/     %br/
/ :javascript
/   //$('#textarea1').val('Write Your Message here');
/    	$('#textarea1').trigger('autoresize');

app/views/partials/_footer.html.haml
%footer.page-footer
  .footer-copyright
    .container
      © 2016 Copyright Onklick Media
      %a.grey-text.text-lighten-4.right{:href => "#!"} More Links
  %div
    .fixed-action-btn.vertical.click-to-toggle{:style => "bottom: 45px; right: 24px;"}
      %a.btn-floating.btn-large.red
        %i.large.mdi-navigation-menu
      %ul
        %li
          %a.btn-floating.red
            %i.material-icons insert_chart
        %li
          %a.btn-floating.yellow.darken-1
            %i.material-icons format_quote
        %li
          %a.btn-floating.green
            %i.material-icons publish
        %li
          %a.btn-floating.blue
            %i.material-icons attach_file

app/views/partials/_googleAnalytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76485229-1', 'auto');
  ga('send', 'pageview');

app/views/partials/_latest_news.html.haml
.news-header.container
  %h1.text-center #Latest News
- @blogs.each_slice(4) do |blogs|
  .row
    - blogs.each do |blog|
      .col.s12.m6.l3
        .news.z-depth-1
          .image-wrapper
            = link_to blog do
              = image_tag blog.image.url(:large)
          = link_to blog do
            .caption-text 
              %h5.text-center
                = blog.title
          %h6.text-center 
            Posted on
            = blog.created_at.to_formatted_s(:long_ordinal)
  / = blog.title
  / = blog.excerpt
  / .items.row
  /   .col.s12.m4.l3
  /     = image_tag blog.image.url(:large), :class => "responsive-img thumb"
  / .col.l4.item2
  /   = image_tag blog.image.url(:large), :class => "img-responsive"
  / .col.l4.item3
  /   = image_tag blog.image.url(:large), :class => "img-responsive"
  / = blog.contents
  / = link_to 'Show', blog
  / = link_to 'Edit', edit_blog_path(blog)
  / = link_to 'Destroy', blog, :method => :delete, :data => { :confirm => 'Are you sure?' }



/ = link_to 'New Blog', new_blog_path

app/views/partials/_market_content.html.haml
.market-wrapper
	.market-inner
		.dot-cover
			#text-caption.container.left-align
				%h1.left-align MARKETING.
				%hr.left-align
				%p.flow-text WE DESIGN GREAT MARKETING CAMPAIGN

.market-body
	.inner-body
		.text-caption.container.text-center
			%h1.flow-text marketing differently.
			%hr
			%p.flow-text Digital, especially mobile, encompasses most everyday aspects of our lives – it’s important to utilise every status, video, pin, tweet, post and more to get in touch with customers. Your potential customers are always just around the corner and you can target them 24/7…
			%p.flow-text Want-to-know moments: When you’re watching a movie and you can’t figure out where you recognise that actor from – so you “Google it!” Consumers have a world of knowledge at their fingertips so they can research anything they like…when they like. Want-to-go moments: Location-based searches, especially nearby facilities such as restaurants and bars, are very popular with a wide demographic. Want-to-do moments: Practical how-to marketing created for users who want to try it out for themselves. This could be cookery, DIY and crafts via video marketing, infographics, an interactive content piece or even just a static blog. Want-to-buy moments: From everyday items such as toilet roll to bigger items such as gig tickets, people can purchase just about anything online. Customers are constantly connected, so they can make quick purchases on the spot or make an informed decision using mini moments on their smartphone throughout the day.
.row.marketing-style
	.container.style-container
		.social-content
			%p.flow-text Social media marketing is one of the fastest growing solutions, this platform will help in optimising your business, it also help generate customers response from all over the world.
		.col.s6.m6.l3.email-marketing.tab
			%i.fa.fa-envelope-o
			%p.text-center.flow-text Email marketing techniques – 
		.col.s6.m6.l3.twitter.tab
			%i.fa.fa-twitter
			%p.text-center.flow-text Creating Twitter contents & post – 
		.col.s6.m6.l3.facebook.tab
			%i.fa.fa-facebook
			%p.text-center.flow-text Facebook page management–
		.col.s6.m6.l3.linkedin.tab
			%i.fa.fa-linkedin
			%p.text-center.flow-text Linkedin professional profile – 
	#email.container
		.row
			.col.s12.m6.l6.email-pix
			.col.s12.m6.l6.email-text
				%h2 Email Marketing
				%p.flow-text Email marketing strategy should be part of your marketing and business plan. The use of this marketing solution can help you promote your products and services with uttermost chances of reaching your profit margin and goals. This effective method of marketing plays an important role by recognising who your target customers, their preferences and their online behaviour towards products and services of interest, in which email marketing will directly lead them to your services
	#twitter.container
		.row
			.col.s12.m6.l6.twitter-text
				%h2 Twitter Account
				%p.flow-text Our social media expert will help create a Compelling content that will help you attract new followers and keep them engaged over time. There’s no right or wrong number of times you should Tweet each day, or when. Instead, we focus on creating a regular cadence of content that’s relevant to your target audience and authentic to your business. 
				/ %ul
				/ 	%li
				/ 		%h5 Keep it short
				/ 	%li
				/ 		%h5 Use visuals in your Tweets
				/ 	%li
				/ 		%h5 Incorporate relevant hashtags
				/ 	%li
				/ 		%h5 Ask questions and run polls
				/ 	%li
				/ 		%h5 Curate and connect with Retweets and replies
			.col.s12.m6.l6.twitter-pix	
	#facebook.container
		.row
			.col.s12.m6.l6.facebook-pix
			.col.s12.m6.l6.facebook-text
				%h2 Facebook Page
				%p.flow-text Successful businesses on Facebook today are those that step out from behind their logo and let the people behind the business and brands represent their Facebook page. The aim is to communicate with your fans as if you were talking to your friends, and let your personality come through in each post. One of the ways to do this is to step away from your niche once in a while and show your personal side through entertaining posts and photos. Change things up a bit and share details about your experiences and everyday life.
	#linkedin.container
		.row
			.col.s12.m6.l6.linkedin-text
				%h2 Linkedin Profile
				%p.flow-text There are over 300 million members on LinkedIn. But this isn't a numbers game, it's about reaching the people that matter most to your business. It's about focusing on the people who have already shown interest in your products and services. Luckily, LinkedIn makes it easy to identify your audience and determine which audience segments are engaging with your various types of content. We create linked page that draws your audience to your product and services.
			.col.s12.m6.l6.linkedin-pix
= render 'partials/company_image'	

app/views/partials/_navbar.html.haml
#page-top.navbar-fixed{"data-spy" => "scroll"}
  %nav#nagbar{:role => "navigation"}
    .nav-wrapper.page-scroll
      %a.brand-logo{:href => "#page-top"}
        %img{:src => "/assets/header_logo_white.png"}/
      %a.button-collapse{"data-activates" => "slide-out", :href => "#"}
        %i.material-icons menu
      %ul.right.hide-on-med-and-down
        %li.hidden
          %a.page-scroll{:href => "#page-top"}
        %li
          %a.page-scroll{:href => "#company"} COMPANY
        %li
          %a.page-scroll{:href => "#services"} SERVICES
        %li
          %a.page-scroll{:href => "#contact"} CONTACT
        %a#nbtn.waves-effect.waves-light.btn Get Started
      %ul#slide-out.side-nav
        .chip-contianer.center-align
          .chip
            %img{:alt => "Contact Person", :src => "/assets/Team-4.png"}/
            Austin Oseh
            %h6 Developer
        .sidebar-nav
          %li
            %a{:href => "sass.html"} SERVICES
          %li
            %a{:href => "badges.html"} COMPANY
          %li
            %a{:href => "collapsible.html"} CONTACT
        / Switch
        .switch.center-align
          %label
            Off
            %input{:type => "checkbox"}/
            %span.lever
            On
        .switch.center-align
          %label
            Off
            %input{:type => "checkbox"}/
            %span.lever
            On
:javascript
  $(".button-collapse").sideNav();
  
            $(window).scroll(function() {
      if ($(".navbar").offset().top > 50) {
          $(".navbar-fixed-top").addClass("top-nav-collapse");
      } else {
          $(".navbar-fixed-top").removeClass("top-nav-collapse");
      }
  });
  
  $(function() {
      $('a.page-scroll').bind('click', function(event) {
          var $anchor = $(this);
          $('html, body').stop().animate({
              scrollTop: $($anchor.attr('href')).offset().top
          }, 1500, 'easeInOutExpo');
          event.preventDefault();
      });
  });
  
      //$('.button-collapse').sideNav({
       // menuWidth: 200,
        //menuHeight: 300, // Default is 240
       // edge: 'right', // Choose the horizontal origin
       // closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
     // }
   // );

app/views/partials/_navigation.html.haml
#page-top.navbar-fixed{"data-spy" => "scroll"}
  %nav#nagbar{:role => "navigation"}
    %a.button-collapse.show-on-large{"data-activates" => "slide-out", :href => "#"}
      %i.material-icons.menu menu
      / %i.material-icons.clear clear
    .nav-wrapper.page-scroll
      %a.brand-logo{:href => "/"}
        %img{:src => "/assets/header_logo_white.png"}/
      %ul.right
        %li.hidden
          %a.page-scroll{:href => "#page-top"}
        %li.call-us
          %h6 <span style ="padding-top: 5px; margin-top: 0px; color: #fff; letter-spacing: 2px; display: inline-block;"><strong>Call 020 7635 2679</strong></span>
          %h6.small.text-center <span style ="padding: 0px; margin: 0px; display: inline-block; font-size: 10px;">office open monday-friday</span>
        / %li.top
        /   %a.page-scroll{:href => "/"}
        /     %i.large.material-icons home
        / %li.top
        /   /%a.tooltipped.calls{"data-delay" => "50", "data-position" => "bottom", "data-tooltip" => "Tel: 020 7635 2679, Mob: 07853 292 983"}
        /   %a{:onclick => "Materialize.toast('<h2><strong>Tel: 020 7635 2679, Mob: 07853 292 983</strong></h2>', 8000 )"}
        /     %i.large.material-icons call
        / %li.top
        /   /%a.tooltipped.calls{"data-delay" => "50", "data-position" => "bottom", "data-tooltip" => "Email Us: design@miscotech.co.uk"}
        /   %a{:onclick => "Materialize.toast('<h2><strong>Email Us: design@miscotech.co.uk</strong></h2>', 8000 )"}
        /     %i.large.material-icons email
        %li
          %a.button.btn.waves-effect.waves-light.page-scroll{:href => "#page-top"} <span class="text-center" style = "font-size: 14px; letter-spacing: 1px;">Get a Quote</span>
      %ul#slide-out.side-nav
        %l1.auth
          - if !admin_signed_in?
            = link_to "Sign in", new_admin_session_path
          - else
            = link_to "Sign out", destroy_admin_session_path, method: :delete
          / %i.large.material-icons.z-depth-5.text-center home
        .sidebar-nav
          %li.hidden
            %a.page-scroll{:href => "#page-top"}
          %li.but.first
            %a.page-scroll{:href => "/"}
              %i.fa.fa-home{"aria-hidden" => "true"} <span style = "font-family: Open Sans;  padding-left: 10px;">Home</span>
          %li.but.first
            %a.page-scroll{:href => "/#news"}
              %i.fa.fa-newspaper-o{"aria-hidden" => "true"} <span style = "font-family: Open Sans;  padding-left: 10px;">News</span>
          %li.but.second
            %a.page-scroll{:href => "#"}
              %i.fa.fa.fa-cogs{"aria-hidden" => "true"} <span style = "font-family: Open Sans;  padding-left: 10px;">Services</span>
          %li.but.third
            %a.page-scroll{:href => "/contact"}
              %i.fa.fa-sticky-note-o{"aria-hidden" => "true"} <span style = "font-family: Open Sans;  padding-left: 10px;">Contact</span>
          %li.but.forth
            %a.page-scroll{:href => "/web"}
              %i.fa.fa-tablet{"aria-hidden" => "true"} <span style = "font-family: Open Sans;  padding-left: 10px;">Web Design</span>
          %li.but.fifth
            %a.page-scroll{:href => "/marketing"}
              %i.fa.fa-dot-circle-o{"aria-hidden" => "true"} <span style = "font-family: Open Sans;  padding-left: 10px;">Marketing</span>

          / %li.but.sixth
          /   %a.page-scroll{:href => "#"} BRANDING
        / Switch

:javascript
  $(".button-collapse").sideNav();
  
    $(window).scroll(function() {
      if ($(".navbar").offset().top > 50) {
          $(".navbar-fixed-top").addClass("top-nav-collapse");
      } else {
          $(".navbar-fixed-top").removeClass("top-nav-collapse");
      }
  });
  
  $(function() {
      $('a.page-scroll').bind('click', function(event) {
          var $anchor = $(this);
          $('html, body').stop().animate({
              scrollTop: $($anchor.attr('href')).offset().top
          }, 1500, 'easeInOutExpo');
          event.preventDefault();
      });
  });

   $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });
  
      //$('.button-collapse').sideNav({
       // menuWidth: 200,
        //menuHeight: 300, // Default is 240
       // edge: 'right', // Choose the horizontal origin
       // closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
     // }
   // );

app/views/partials/_our_contact.html.haml
#our-contact
	.inner-contact
		.dotted-cover
			#heading-text.container
				%h1.text-center GET IN TOUCH.
				%p.text-center
				%ul.center
					%li
						%a{:href =>"https://www.facebook.com/onklickmedia", target: "blank"}
							%i.fa.fa-facebook-square
					%li
						%a{:href =>"https://plus.google.com/102704021727611661526", target: "blank"}
							%i.fa.fa-google-plus-square
					%li
						%i.fa.fa-twitter-square
					%li
						%i.fa.fa-youtube-square
					%li
						%a{:href =>"https://www.linkedin.com/in/austin-oseh-515228a6?trk=nav_responsive_tab_profile", target: "blank"}
							%i.fa.fa-linkedin-square 
			.quick-contact.container.center
				%h6.text-center Got new or existing project you want us to work on? Call 02076352679 or 
				%a.waves-effect.waves-light.btn.center.page-scroll.contact-us{:href => "#page-top"} Request a Quote

#contact-us.row
	.form.col.s12.m6.l6
		.map-cover
			.text-wrapper.center
				%h6.text-center 160a New Cross Road
				%h6.text-center London
				%h6.text-center SE14 5AR
				%h6.text-center 02076352679
				%h6.text-center info@onklick.co.uk
				%br
				%h6.text-center Office Open Monday - Friday
				%h6.text-center 10am - 7pm
			/ = render 'contacts/form'

	.address.col.s12.m6.l6
		%iframe{:allowfullscreen => "", :frameborder => "0", :height => "600", :src => "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3575.791575116959!2d-0.049860411246478026!3d51.47597591927426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2suk!4v1460730346800", :style => "border:0; background-color: black; opacity: 0.6;", :width => "100%"}
			

app/views/partials/_process.html.haml
.process
	.container.process-header
		%h1.center-align HOW WE DO.
		%hr
		%h6.center-align.flow-text We adopt this process to provide high level services and support
	.row.process-wrapper
		.container.c-wrapper.flex-container
			.col.s6.m4.l2#sign-up.z-depth-2
				%h2 Sign up
				%i.fa.fa-pencil-square-o
			.col.s6.m4.l2#research.z-depth-2
				%h2 Research
				%i.fa.fa-search
			.col.s6.m4.l2#design.z-depth-2
				%h2 Design
				%i.fa.fa-gavel
			.col.s6.m4.l2#build.z-depth-2
				%h2 Build
				%i.fa.fa-code
			.col.s6.m4.l2#launch.z-depth-2
				%h2 Launch
				%i.fa.fa-external-link
			.col.s6.m4.l2#support.z-depth-2
				%h2 Support
				%i.fa.fa-life-ring

app/views/partials/_quote.html.haml
#quotation
	.quote-wrapper
		%br
		%br
		%br
		%h2.text-center get a quote.
		%p.text-center tell us about your project and what you want to achieve & we will design a strategy to reach your goals. 
		%p.text-center Alternatively speak to one of our team on  <strong style = "font-size: 18px; color: #02C39A;">020 7635 2679.</strong>
		%br
		.container.inner
			= render "quotations/form"

app/views/partials/_static_background.html.haml
#img-bg
  %img.responsive-img{:src => "/assets/slide1.png"}/
  .jumbotron.text-center
    %a.waves-effect.waves-light.btn-floating
      %i.material-icons.right> cloud
      button
    %p THIS IS THE NEW ERA WEBSITE

app/views/partials/_testimony.html.haml
.slider
  %ul.slides
    %li
      %img{:src => "http://lorempixel.com/580/250/nature/1"}
        / random image
        .caption.center-align
          %h3 This is our big Tagline!
          %h5.light.grey-text.text-lighten-3 Here's our small slogan.
    %li
      %img{:src => "http://lorempixel.com/580/250/nature/2"}
        / random image
        .caption.left-align
          %h3 Left Aligned Caption
          %h5.light.grey-text.text-lighten-3 Here's our small slogan.
    %li
      %img{:src => "http://lorempixel.com/580/250/nature/3"}
        / random image
        .caption.right-align
          %h3 Right Aligned Caption
          %h5.light.grey-text.text-lighten-3 Here's our small slogan.
    %li
      %img{:src => "http://lorempixel.com/580/250/nature/4"}
        / random image
        .caption.center-align
          %h3 This is our big Tagline!
          %h5.light.grey-text.text-lighten-3 Here's our small slogan.



:javascript
  $(document).ready(function(){
    $('.slider').slider({full_width: true});
  });

app/views/partials/_web_contents.html.haml
.web-wrapper
	.web-inner
		.dot-cover
			.text-caption.center-align
				%h1.center-align WEB.
				%hr
				%p.flow-text WE DESIGN AFFORDABLE WEBSITES
			.row.weblock
				.col.s3.m3.l3

				.col.s3.m3.l3
		
				.col.s3.m3.l3

				.col.s3.m3.l3


.page-text-bg
	.page-cover
		.container
			.web-icon.text-center
				%i.large.material-icons.z-depth-5 description
			%p.center.flow-text starting any web development project with a discovery phase where we can research exactly what your potential customers are looking for using a vast range of powerful industry research tools. 
			%br
			%p.center.flow-text Beginning to redesign your website we first take our time to understand your audience and what they want from your business . If your business cannot afford to fail then using our discovery  and research service may be the way forward. Our team here at Onklick Media have carried out a number of discovery phases for many businesses throughout the past 5 years.
			%br
			%p.center.flow-text Our access to data via our <em style ="color: green;">Google Partner Status</em> allows our research to reach beyond basic analytical tools and identify deep industry trends, where your customers most commonly go when searching for your products and services, the types of devices they most commonly use and so much more. Analysing this data can allow us to design the perfect website to precisely meet your customers’ needs and ensure visitors turn into customers. Advance web development solutions that will help improve your business, all design and development  are tailored to your company’s needs with non-stop technical support and project management.Our digital designs will meet all your company’s standard. 
.row.design-types
	.item-wrapper.col.s12.m6.l3
		.property
			#property-wrapper
				%h1.text-center Property
				%h6.text-center Expert in property website design
				%hr
	.item-wrapper.col.s12.m6.l3
		.business
			#business-wrapper
				%h1.text-center Business
				%h6.text-center Outstanding business website
				%hr
	.item-wrapper.col.s12.m6.l3
		.showcase
			#showcase-wrapper
				%h1.text-center Showcase
				%h6.text-center Display your product & Services
				%hr
	.item-wrapper.col.s12.m6.l3
		.ecommerce
			#ecommerce-wrapper
				%h1.text-center Ecommerce
				%h6.text-center Sell your goods and services
				%hr

.features
	.blue.light-dots
		.container
			%h1.text-center FEATURES
			%hr 
			%h6.text-center What you get with our web design package
			%ul
				%li.feature-item
					%i.fa.fa-tablet
					%h2.flow-text RESPONSIVE
					%p.flow-text Responsive websites allow a site to adapt to different screen sizes enabling you to offer any visitor the best possible experience
				%li.feature-item
					%i.fa.fa-sticky-note-o
					%h2.flow-text UNLIMITED PAGES
					%p.flow-text You can choose any number of pages that best suite your business.
				%li.feature-item
					%i.fa.fa-gear
					%h2.flow-text CMS
					%p.flow-text You can update your site whenever you wish and we also offer technical support for the life of your website.
				%li.feature-item
					%i.fa.fa-mobile
					%h2.flow-text MOBILE FRIENDLY
					%p.flow-text This makes your website looks great on mobile phone.
				%li.feature-item
					%i.fa.fa-check-square-o
					%h2.flow-text FREE DOMAIN NAME
					%p.flow-text We will include a new UK domain name or you can also use one you already own. comes with business email addresses as standard.
				%li.feature-item
					%i.fa.fa-file-text
					%h2.flow-text FORMS
					%p.flow-text Allow website visitors to complete an enquiry form and have that form sent directly to your email address so that you can respond.
#process
	= render 'partials/process'
.call-to-action
	.call-cover
		.container
			%h4.text-center INTERESTED IN SIGNING UP FOR OUR WEB DESIGN PACKAGE
			.row.package-buttons
				.col.s6.solid-button
					%a.waves-effect.waves-light.btn-large.page-scroll{:href => "#page-top"} GET A QUOTE
				.col.s6.border-button
					%a.waves-effect.waves-light.btn-large{:href => "#"} GET IN TOUCH
.caret-pop.container
	.arrow-down
#contacts
	/= render 'contacts/form'
#company-image
	= render 'partials/company_image'

:javascript
	var options = [
		{selector: '.design-types', offset: 250, callback: 'Materialize.fadeInImage(".design-types")' },
		{selector: '.features', offset: 400, callback: 'Materialize.fadeInImage(".features")' },
		{selector: '#process', offset: 200, callback: 'Materialize.fadeInImage("#process")' },
		{selector: '.call-to-action', offset: 150, callback: 'Materialize.fadeInImage(".call-to-action")' },
		{selector: '#contacts', offset: 150, callback: 'Materialize.fadeInImage("#contacts")' },
		{selector: '#company-image', offset: 400, callback: 'Materialize.fadeInImage("#company-image")' }
	];
	Materialize.scrollFire(options);