config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  resources :works
  resources :blogs
  resources :quotations
  resources :contacts
  root 'pages#home'
  get 'marketing' => 'pages#marketing'
  get 'company' => 'pages#company'
  get 'news' => 'pages#news'
  get 'contact' =>  'pages#contact'
  get 'web' => 'pages#webdesign'
  get 'projects' => 'pages#projects'

end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	validates :name, :company, :email, presence: true
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to root_path, notice: 'Your information was successfully submitted.' }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:name, :company, :email, :telephone, :message)
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.haml
.quote
  / %p#notice= notice
  = form_for @quotation, remote: true do |f|
    - if @quotation.errors.any?
      #error_explanation
        %h2= "#{pluralize(@quotation.errors.count, "error")} prohibited this quotation from being saved:"
        %ul
          - @quotation.errors.full_messages.each do |msg|
            %li= msg
    %form
      .row
        .input-field.col.s12
          / %i.material-icons.prefix mode_edit
          = f.text_field :name, class: "name-field"
          %label{:for => "name"} Name
      %br    
      .row
        .input-field.col.s12
          = f.text_field :company, class: "company-field"
          %label{:for => "company"} Company
      %br  
      .row
        .input-field.col.s12
          = f.text_field :email, class: "email-field"
          %label{:for => "email"} Email
      %br  
      .row
        .input-field.col.s12
          = f.text_field :telephone, class: "telephone-field"
          %label{:for => "telephone"} Telephone
      %br  
      .row
        .input-field.col.s12
          = f.text_area :message, class: "materialize-textarea", id: "textarea1", :length => "225"
          %label{:for => "textarea1"} Message
      %br
      .row
        .submit-btn.container.text-center.col.s12
          %button#submit-button.btn.waves-effect.waves-light
            = f.submit 'Submit.', remote: true
:javascript
  //$('#textarea1').val('Write Your Message here');
  $('#textarea1').trigger('autoresize');

  $(document).ready(function() {
    $('input#input_text, #textarea1').characterCounter();
  });
       

app/views/quotations/create.js.erb
$("#quotation").hide();
$('#modal1').openModal();
$(".name-field").val('');
$(".company-field").val('');
$(".telephone-field").val('');
$(".email-field").val('');
$(".materialize-textarea").val('');

app/views/quotations/edit.html.haml
%h1 Editing quotation

= render 'form'

= link_to 'Show', @quotation

= link_to 'Back', quotations_path

app/views/quotations/index.html.haml
.container
  %h1 Listing quotations

  %table
    %thead
      %tr
        %th Name
        %th Company
        %th Email
        %th Telephone
        %th Message
        %th
        %th
        %th

    %tbody
      - @quotations.each do |quotation|
        %tr
          %td= quotation.name
          %td= quotation.company
          %td= quotation.email
          %td= quotation.telephone
          %td= quotation.message
          %td= link_to 'Show', quotation
          %td= link_to 'Edit', edit_quotation_path(quotation)
          %td= link_to 'Destroy', quotation, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New Quotation', new_quotation_path

app/views/quotations/new.html.haml
.container
	%h1 New quotation

	= render 'form'

	= link_to 'Back', quotations_path

app/views/quotations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @quotation.name
%p
  %b Company:
  = @quotation.company
%p
  %b Email:
  = @quotation.email
%p
  %b Telephone:
  = @quotation.telephone
%p
  %b Message:
  = @quotation.message

= link_to 'Edit', edit_quotation_path(@quotation)
\|
= link_to 'Back', quotations_path